baseURL = "https://www.recetasurfera.cl"
languageCode = "es-cl"
title = "Surf Prescriptions Chile"
theme = "infinity-hugo"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]

    # Navigation
    [params.navigation]
        home = "Inicio"
        about = "Quiénes somos"
        service = "Doc en Chile"
        contact = "Contactanos"

    # Hero Area
    [params.hero]
        enable      = true
        bg          = "images/doc shaperoom.jpg"
        title       = "Jeff 'Doc' Lausch en Chile!"
        subtitle    = "Haz tu tabla soñada a la medida. Cupos limitados"
        btnText     = "Más información"
        countdownYear = "2019"
        countdownMonth = "03"
        countdownDay  = "22"

    # About Section
    [params.about]
        enable      = true
        heading     = "Distribuidores exclusivos de Surf Prescriptions en Chile"
        description = "Surf Prescriptions es la marca del shaper Jeff 'Doc' Lausch, de Huntington Beach, California. Doc fábrica tablas hace 40 años, y las sigue fabricando él, sin relegar a terceros ni acudir a producción en masa en otros países. Usa los mejores materiales del mercado. Team riders incluyen Coco Nogales, Rafael Tapia, CJ Kanuha, Donavon Frankenreiter, Vince Boulanger y Tyler Gunter, entre otros. **Doc estará en Chile desde el 22 de Marzo al 3 de Abril fabricando tablas!. Haz tu nave a medida, hecha por DOC Contáctanos en recetasurfera@gmail.com**"

        [[params.about.sliderItem]]
            image   = "images/about/afiche.jpg"

    
    # Service Section
    [params.service]
        enable      = true
        title       = "Haz tu nave con Doc"
        subtitle    = "Una colaboracíon con Puntas del Sur y Olaf Shapes"
        [[params.service.serviceItem]]
            # give icon(themefisher icon font), title, description
            # more about themefisher icon font visit https://github.com/themefisher/themefisher-font
            # use delay for reveal items one by one
            icon    = "tf-beaker"
            title   = "Hecha a la medida"
            description = "Lorem ipsum dolor sit amet, con-sectetur adipisicing elit, sed do eiusmod tempor incididunt ut"
            delay   = "0s"

        [[params.service.serviceItem]]
            # give icon(themefisher icon font), title, description
            # more about themefisher icon font visit https://github.com/themefisher/themefisher-font
            # use delay for reveal items one by one
            icon    = "tf-tools"
            title   = "Doc shapea tu tabla"
            description = "Lorem ipsum dolor sit amet, con-sectetur adipisicing elit, sed do eiusmod tempor incididunt ut"
            delay   = "0.2s"

        [[params.service.serviceItem]]
            # give icon(themefisher icon font), title, description
            # more about themefisher icon font visit https://github.com/themefisher/themefisher-font
            # use delay for reveal items one by one
            icon    = "tf-ion-eye"
            title   = "Live Shaping"
            description = "Lorem ipsum dolor sit amet, con-sectetur adipisicing elit, sed do eiusmod tempor incididunt ut"
            delay   = "0.4s"

        [[params.service.serviceItem]]
            # give icon(themefisher icon font), title, description
            # more about themefisher icon font visit https://github.com/themefisher/themefisher-font
            # use delay for reveal items one by one
            icon    = "tf-chat"
            title   = "Meet and greet DOC"
            description = "Lorem ipsum dolor sit amet, con-sectetur adipisicing elit, sed do eiusmod tempor incididunt ut"
            delay   = "0.6s"
        
        [[params.service.serviceItem]]
            # give icon(themefisher icon font), title, description
            # more about themefisher icon font visit https://github.com/themefisher/themefisher-font
            # use delay for reveal items one by one
            icon    = "tf-circle-compass"
            title   = "Materiales Premium"
            description = "Lorem ipsum dolor sit amet, con-sectetur adipisicing elit, sed do eiusmod tempor incididunt ut"
            delay   = "0.8s"

        [[params.service.serviceItem]]
            # give icon(themefisher icon font), title, description
            # more about themefisher icon font visit https://github.com/themefisher/themefisher-font
            # use delay for reveal items one by one
            icon    = "tf-book-open"
            title   = "Personal de apoyo calificado"
            description = "Lorem ipsum dolor sit amet, con-sectetur adipisicing elit, sed do eiusmod tempor incididunt ut"
            delay   = "1s"

        [[params.service.serviceItem]]
            # give icon(themefisher icon font), title, description
            # more about themefisher icon font visit https://github.com/themefisher/themefisher-font
            # use delay for reveal items one by one
            icon    = "tf-ion-clock"
            title   = "Cupos limitados"
            description = "Lorem ipsum dolor sit amet, con-sectetur adipisicing elit, sed do eiusmod tempor incididunt ut"
            delay   = "1.2s"

        [[params.service.serviceItem]]
            # give icon(themefisher icon font), title, description
            # more about themefisher icon font visit https://github.com/themefisher/themefisher-font
            # use delay for reveal items one by one
            icon    = "tf-ion-social-instagram-outline"
            title   = "Síguenos en redes sociales"
            description = "Lorem ipsum dolor sit amet, con-sectetur adipisicing elit, sed do eiusmod tempor incididunt ut"
            delay   = "1.5s"
    
    [params.contact]
        enable      = true
        title       = "Escribénos"
        subtitle    = "Pra más detalles, escribenos a recetasurfera@gmail.com"
